version: '3.8'

services:
  app:
    container_name: backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
    restart: always  
    
  frontend:
    container_name: frontend
    build:
      context: ./front-end  
      dockerfile: Dockerfile
    ports:
      - '3001:3001' 
    depends_on:
      - app  
    environment:
      REACT_APP_API_URL: http://app:3000  
    networks:
      - app-network
    restart: always  

networks:
  app-network:
    driver: bridge
