version: '3.8'

services:
  app:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
    restart: always  
    
  frontend:
    container_name: frontend
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - '3001:3001' 
    depends_on:
      - app   
    networks:
      - app-network
    restart: always  

networks:
  app-network:
    driver: bridge
