name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # ou outra branch de sua preferência

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar o SSH para acessar o servidor DigitalOcean
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}

      # 3. Conectar ao servidor e realizar o deploy
      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_SSH_HOST }} << 'EOF'
            cd /home/deploy/myproject || exit
            git pull origin main || exit
            docker-compose down || exit
            docker-compose up -d --build || exit
          EOF
